# Generated by Django 5.0 on 2023-12-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('ano_publicacao', models.IntegerField()),
                ('descricao', models.TextField(blank=True)),
                ('isbn', models.CharField(max_length=30)),
                ('emprestado', models.BooleanField(default=False)),
                ('doado', models.BooleanField(default=False)),
                ('avaliacao', models.FloatField()),
                ('nome_pessoa_empr', models.CharField(max_length=250)),
                ('data_emprest_doa', models.DateField()),
            ],
        ),
    ]
