# Generated by Django 5.0 on 2023-12-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='data_emprest_doa',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='nome_pessoa_empr',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
