# Generated by Django 5.0 on 2023-12-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_alter_livro_data_emprest_doa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='data_emprest_doa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='nome_pessoa_empr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
