# Generated by Django 5.0 on 2023-12-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0004_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='login',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
